<?php

/**
 * Class PostsSeeder
 *
 * Auto-generated by Sprint on 2015-03-20 03:43am
 */
class PostsSeeder extends Seeder {

	public function run()
	{
        $this->ci->load->model('post_model');

        $faker = \Faker\Factory::create();

        for ($i=1; $i <= 10; $i++)
        {
            $data = [
                'title' => $faker->sentence(),
                'body'  => implode("\n\n", $faker->paragraphs(4) ),
                'deleted' => 0
            ];

            $this->ci->post_model->skip_validation()->insert($data);
        }
	}

	//--------------------------------------------------------------------

}